### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by ceobillionaire** [openai/rosbridge#1]
The link https://github.com/openai/fetch_setup is not working (_I'm getting a 404 error_).

**Comment by ceobillionaire** [comment]
In the `README.md` at the section **Installation on a Fetch** (https://github.com/openai/rosbridge#installation-on-a-fetch), the link https://github.com/openai/fetch-config (installation scripts) is not working (_I'm getting a 404 error_).

**Comment by wojzaremba** [comment]
We have merged several repositories in one called fetch-config. Currently, fetch-config contains configuration which is quite specific to what we have in our lab. I don't want to release half-baked code.
