### ISSUE TITLE
"timeseq" package required for fetch_proxy.py

### ISSUE THREAD

**Issue by cannontwo** [openai/rosbridge#2]
The script `fetch_proxy.py` appears to require a package called "timeseq", but I am unable to find this as a Python package anywhere. Is this a reference to an unincluded file, or is there some missing documentation indicating where to locate this package?

We would like to use this repository for our research, but are having trouble launching the ROS node because of this missing dependency.

**Comment by tlbtlbtlb** [comment]
Added in https://github.com/openai/rosbridge/commit/7f6627f0d047d7395201e64061654f8eca8dc2de

**Comment by cannontwo** [comment]
Thanks much!
